### PR TITLE
Added option to open Streamlink from ChatControl

### PR DESCRIPTION
**Pull request by Cranken**
This adds a option to open Streamlink from the ChatControl header. The quality of Streamlink can be selected in the appearance tab of the settings. The default value is "best".  
This works for almost all streams except non-partnered and for streams with custom quality options("best" and "worst" will always work).  
Could also move the quality setting in a pop-up which opens after you click the "Open Streamlink" button.

### CODE REVIEW

**Comment by fourtf** [comment]
I think there should be an option to select the streamlink binary instead of starting it from %path% and the current directory, what do you think?

**Comment by Cranken** [comment]
I mean it's not very hard to implement but the Streamlink installer adds itself to %path% automatically and I doubt many people use the portable version. But if you want I could add the option.  
Btw. if you have any idea concerning the quality options, let me know.

**Comment by fourtf** [comment]
At least there should be an error message telling you that you need the non-portable version of streamlink if it fails

**Comment by fourtf** [comment]
can I merge?

**Comment by Cranken** [comment]
Yea sure, go ahead.

**Pull request merged**
